FROM oven/bun:1

# Install OpenSSL and curl for Prisma compatibility and healthchecks
RUN apt-get update -y && apt-get install -y openssl curl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend


RUN bun install 
RUN bun run db:generate

EXPOSE 3001 
CMD [ "bun", "run", "start:backend" ]
